### ISSUE TITLE
transforms.conf entry not created for lookup

### ISSUE THREAD

**Issue by MattUebel** [LukeMurphey/lookup-editor#25]
creating a kvstore in lookup-editor results in a collections.conf entry being created, but no matching lookup definition in transforms.conf

This results in some issue (splunk throws a 404 when trying to hit /storage/collections/config to edit the lookup). There are other reasons to have a lookup definition to match the collection definition, and it should be created.

**Comment by LukeMurphey** [comment]
The app doesn't currently create the transform automatically. However, you can get the app to create one by clicking "Open in Search" from the list page or from the editor. A dialog will appear if no transform exists so that you can make the transform name whatever you wish.

I considered having it automatically created but I was worried about assigning a name automatically. I could auto-create it though if that is something people want.
