### ISSUE TITLE
Feature Request - Add "Open in Search" with Actions

### ISSUE THREAD

**Issue by jdeer0618** [LukeMurphey/lookup-editor#4]
I am a huge fan of the lookup editor but I often want to open the lookup in search. 

what would it take to add that feature?

**Comment by Muryoutaisuu** [comment]
you mean `|inputlookup myfile.csv`  ?

**Comment by jdeer0618** [comment]
yep... Right now I have a dashboard that calls the Knowledge REST endpoint for all lookups. In the results I have an action field with an "Open in Search" drilldown that just does `| inputlookup mylookup.csv`
![screenshot_47](https://cloud.githubusercontent.com/assets/4651176/19207819/8c79b390-8cb9-11e6-9959-34c19b949459.png)

**Comment by LukeMurphey** [comment]
That's totally doable!

I actually do something similar with the Website Input app which allows you to preview the results of the input by running a search command in the search view.

**Comment by LukeMurphey** [comment]
I added this to version 2.4.0. I haven't made 2.4.0 the default release yet so you will have to manually select on Splunk-base in order to download it. I'll make it the default soon. Note that KV store lookups that don't have a transforms.conf entry will not be listed as being able to be opened in search (since they need a transforms.conf to be used with inputlookup).
