### ISSUE TITLE
Python 3 readiness (warning)

### ISSUE THREAD

**Issue by sdesruelles** [LukeMurphey/lookup-editor#48]
Hi,

Thank you for the work you provide regarding this app which is hugely used here.
I got warnings on 2 files when trying the Splunk Upgrade Readiness app (for 8.0 upgrade)
Would you mind taking a look at that?
It seems, it is mostly for Python 2 - 3 compatibility.

* .../bin/six.py

![image](https://user-images.githubusercontent.com/64398251/80342192-ff9f6f00-8863-11ea-989d-62d0fb370c6b.png)
![image](https://user-images.githubusercontent.com/64398251/80342262-2067c480-8864-11ea-921a-3b7b59b5be6c.png)
![image](https://user-images.githubusercontent.com/64398251/80342276-29f12c80-8864-11ea-943f-863f85efe2cf.png)

* .../bin/lookup_editor/flatten.py

![image](https://user-images.githubusercontent.com/64398251/80342369-55741700-8864-11ea-883e-d1331737ad2f.png)

Many thanks in advance.

Regards,
S. Desruelles

**Comment by LukeMurphey** [comment]
The Lookup Editor is Python 3 compliant. I have done extensive testing to confirm this and have a sophisticated set of unit tests to confirm it too. Many (including myself) are already running the app in Splunk 8.0 without problems and have been doing so for for a while.

These are almost certainly false positives in the upgrade readiness app. This especially likely since it is flagging six.py (which is a library to _help_ apps get compliant with Python 3).

**Comment by sdesruelles** [comment]
Sure thing, thanks for your feedback.
