### ISSUE TITLE
XSS permitted in table view

### ISSUE THREAD

**Issue by moonman81** [LukeMurphey/lookup-editor#57]
During recent works - I loaded data into Lookup Editor which came from user-populated fields. This included XSS attempts in the data placed by previous penetration testers. While that data is silently dropped from Splunk's 'lookup' commands, it shows in Lookup Editor and permits script execution when it happens.
![xss-redacted](https://user-images.githubusercontent.com/5961892/87672890-91d05880-c76b-11ea-930f-d86a18b6ced1.png)
This is on version 3.4.1 and I can reproduce it on 3.4.4 as well
While Lookup editor will not permit me to introduce any XSS attempts, it faithfully processes what is in the CSV (which may not have been generated by splunk)

**Comment by LukeMurphey** [comment]
I'll fix this ASAP. I have an XSS test case.

**Comment by moonman81** [comment]
ty for your expedient response

**Comment by LukeMurphey** [comment]
Fixed in version 3.4.6 (on Splunk base now).

This was a weird issue. The table has sanitization functions which did filter issues. However, there was an issue with the version of one of the libraries I was using which caused the issue before my sanitizer functions ran. I updated the libraries and re-tested everything to try to make sure no regressions were caused by the upgrade.

You will need to bump Splunk to get the newer front-end to load (see https://bitly.com/ClearTheCache).
