### ISSUE TITLE
The lookup could not be loaded from the server

### ISSUE THREAD

**Issue by mayanakhan** [LukeMurphey/lookup-editor#61]
We have error on the server while trying to open the csv lookup in UI which end with the error `The lookup could not be loaded from the server`  Also we can see different owners for the same lookup in different search head instance. 

ABC lookup owner is Admin in SH1
ABC lookup owner is  user in SH2

Can you please let us know how can we fix this issue. 

We are using latest lookup editor version **3.4.6**

**Comment by jaihingorani777** [comment]
Hi @mayanakhan i have observed the same issue in my environment. I was able to reproduce this scenario in my local (by taking the exact csv lookup from the server). It was a small edit(example randomly remove last row) resolved this. I have tested this with 3-4 versions of this app with the affected .csv file, and the behavior was same. so to fix this, 
1. export csv from splunk, 
2. delete the lookup in splunk UI,
3. open csv in local and randomely remove last entry.
4. save it and upload it.
5. open  via lookup editor.
6. add back removed entry manually again.

i think this behavior is because of some issue happens at the time of saving the lookup file, which will be good if more logging is added in this lookup_editor app logs then it will be easy to drilldown into more. maybe validate the lookup characters before saving it(in case some validation of unsupported characters etc ?)
@LukeMurphey
